"use client"

import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import SwapTracker from "./components/SwapTracker";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (typeof window === "undefined" || !isMounted) {
    return (<div></div>)
  }

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <div style={{ width: "100%", display: "flex", justifyContent: "space-between", padding: 8 }}>
          <h2> Uniswap V3 Swap Tracker On Polygon </h2>
          <ConnectButton />
        </div>

        <SwapTracker />
      </main>
    </div>
  );
};

export default Home;
